### ISSUE TITLE
Template changes.

### ISSUE THREAD

**Issue by danmaclean** [TeamMacLean/effector_class_ms#6]
Recent pull broke the template, and wouldn't add author names.

Please leave the template as svm_latex.tex, and build accordingly.

**Comment by ruthkr** [comment]
The `svm_latex.tex` file has not been included in any of the commits, so I just commented the parameter on the YAML header to be able to compile the manuscript. Could you please add it to the remote repository?

**Comment by danmaclean** [comment]
Looks like *.tex was in .gitignore. Fixed.
